Lb/better logs
tenex/rails-assets pull request #406
Opened 2017-05-05 17:24 UTC by mynameiswillporter

This change decreases logging noise as well as converts our application logs entirely to JSON.  This is to simplify programmatic parsing of the logs for integration with our elastic stack.

2017-05-05 19:11 UTC, hut8 requested changes

2017-05-05 19:11 UTC, hut8 commented on infrastructure/provision-rails-assets.yml
> +      get_url:
Let's get this from the elasticsearch repo

2017-05-05 19:11 UTC, hut8 commented on infrastructure/provision-rails-assets.yml
> +        log_format logstash_json '{ "@timestamp": "$time_iso8601", '
Neat. I had no idea about this. What about json escaping, though? Like if someone puts a `"` in their useragent string?

2017-05-05 19:11 UTC, hut8 commented on config/initializers/colorful_logger.rb
>      color = SEVERITY_TO_COLOR_MAP[severity]
This whole file is stupid; we should get rid of it

2017-05-05 19:11 UTC, hut8 commented on infrastructure/provision-rails-assets.yml
> +                       '"http_referrer": "$http_referer", '
What happens when someone has a `"` in their useragent string?

2017-05-05 19:11 UTC, hut8 commented on infrastructure/provision-rails-assets.yml
> +    - name: create downloads directory
We don't need this if we pull it from the repo

2017-05-05 19:11 UTC, hut8 commented on infrastructure/provision-rails-assets.yml
> +      command: "/etc/init.d/filebeat start"
We should use 
```
service: 
  name: filebeat
  state: started
```

2017-05-06 06:08 UTC, mynameiswillporter commented on config/initializers/colorful_logger.rb
>      color = SEVERITY_TO_COLOR_MAP[severity]
I originally erased the whole file, but many logs were still not in JSON format.  I removed the coloring and custom log levels from the file and renamed it JSON logger.  This allows it to put the rest of the logs in JSON format.

2017-05-06 06:09 UTC, mynameiswillporter commented on infrastructure/provision-rails-assets.yml
> +                       '"http_referrer": "$http_referer", '
Good call, I updated the escaping from 'default' to 'json'.

2017-05-06 16:45 UTC, hut8 approved these changes

2017-05-06 16:45 UTC, merged

2017-05-06 17:29 UTC, hut8 commented on infrastructure/provision-rails-assets.yml
> +                       '"http_referrer": "$http_referer", '
I just deployed this and realized:

```
The escape parameter (1.11.8) allows setting json or default characters escaping in variables, by default, default escaping is used.
```

We're on nginx 1.10.2 ☹️